In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
housing =pd.read_csv("Data.csv")
housing.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05

In [3]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
dtypes: float64(6)
memory usage: 234.5 KB

In [4]:
X=housing.drop('Price',axis=1)
X_test=X[4000:]
X_train=X[0:3999]
Y=housing["Price"]

Y_test=Y[4000:,]
Y_train=Y[0:3999,]
Y_train=Y_train.to_numpy()
Y_train=np.reshape(Y_train, (3999, 1))

In [5]:
X_train.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
count,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000
mean,68561.838573,5.982463,6.989302,3.974744,36279.306301
std,10694.829520,0.990793,1.004513,1.231587,9901.227667
min,17796.631190,2.644304,3.236194,2.000000,172.610686
25%,61473.333995,5.334542,6.308549,3.140000,29549.663810
50%,68656.906770,5.969801,7.001637,4.040000,36241.300990
75%,75781.478130,6.664087,7.665622,4.490000,43005.008470
max,107701.748400,9.519088,10.759588,6.500000,69592.040240

In [6]:
def feature_norm(X):
    X_norm=X
    mean=X.mean()
    std=X.std()
    X_norm=(X-mean)/std
    return X_norm,mean,std;
X_norm,mean,std=feature_norm(X_train)

In [28]:
def gradient_des(X,y,theta,alpha,num_iters):
    m=len(y)
    for iter in range(num_iters):
        sq=np.dot(X,theta)
        ans=sq-y
        l=np.dot(np.transpose(X),ans)
       c=alpha/m
        theta=theta-c*l
        print(iter)
        print(theta)
        print()
    return theta
theta=np.zeros([5,1],dtype=np.float64)




gradient_des(X_train,Y_train,theta,0.1,100)

0
[[8.71373222e+09]
 [7.54669711e+05]
 [8.75741648e+05]
 [4.99019848e+05]
 [4.62479910e+09]]

1
[[-5.34564016e+18]
 [-4.57584418e+14]
 [-5.34852152e+14]
 [-3.04381184e+14]
 [-2.82062304e+18]]

2
[[3.27528720e+27]
 [2.80356465e+23]
 [3.27697304e+23]
 [1.86491225e+23]
 [1.72803345e+27]]

3
[[-2.00673460e+36]
 [-1.71771439e+32]
 [-2.00776668e+32]
 [-1.14261206e+32]
 [-1.05874649e+36]]

4
[[1.22950511e+45]
 [1.05242547e+41]
 [1.23013745e+41]
 [7.00066344e+40]
 [6.48682784e+44]]

5
[[-7.53304802e+53]
 [-6.44809976e+49]
 [-7.53692227e+49]
 [-4.28923258e+49]
 [-3.97441093e+53]]

6
[[4.61541899e+62]
 [3.95068265e+58]
 [4.61779270e+58]
 [2.62796751e+58]
 [2.43507962e+62]]

7
[[-2.82781848e+71]
 [-2.42054155e+67]
 [-2.82927283e+67]
 [-1.61012795e+67]
 [-1.49194757e+71]]

8
[[1.73257453e+80]
 [1.48304025e+76]
 [1.73346560e+76]
 [9.86508396e+75]
 [9.14100526e+79]]

9
[[-1.06153012e+89]
 [-9.08643104e+84]
 [-1.06207607e+85]
 [-6.04423279e+84]
 [-5.60059741e+88]]

10
[[6.50388299e+97]
 [5.56716036e+93]
 [6.50722794e+93]
 [3.70323762e+93]
 [3.43142691e+97]]

11
[[-3.98486044e+106]
 [-3.41094038e+102]
 [-3.98690986e+102]
 [-2.26893459e+102]
 [-2.10239904e+106]]

12
[[2.44148192e+115]
 [2.08984716e+111]
 [2.44273758e+111]
 [1.39015227e+111]
 [1.28811769e+115]]

13
[[-1.49587020e+124]
 [-1.28042729e+120]
 [-1.49663952e+120]
 [-8.51731618e+119]
 [-7.89216111e+123]]

14
[[9.16503876e+132]
 [7.84504282e+128]
 [9.16975235e+128]
 [5.21846970e+128]
 [4.83544379e+132]]

15
[[-5.61532248e+141]
 [-4.80657491e+137]
 [-5.61821045e+137]
 [-3.19730129e+137]
 [-2.96262536e+141]]

16
[[3.44044880e+150]
 [2.94493770e+146]
 [3.44221823e+146]
 [1.95895274e+146]
 [1.81516928e+150]]

17
[[-2.10792666e+159]
 [-1.80433224e+155]
 [-2.10901077e+155]
 [-1.20022966e+155]
 [-1.11213505e+159]]

18
[[1.29150441e+168]
 [1.10549531e+164]
 [1.29216863e+164]
 [7.35368043e+163]
 [6.81393405e+167]]

19
[[-7.91291115e+176]
 [-6.77325306e+172]
 [-7.91698077e+172]
 [-4.50552236e+172]
 [-4.17482545e+176]]

20
[[4.84815712e+185]
 [4.14990064e+181]
 [4.85065053e+181]
 [2.76048598e+181]
 [2.55787148e+185]]

21
[[-2.97041468e+194]
 [-2.54260031e+190]
 [-2.97194237e+190]
 [-1.69132062e+190]
 [-1.56718085e+194]]

22
[[1.81994171e+203]
 [1.55782436e+199]
 [1.82087771e+199]
 [1.03625429e+199]
 [9.60195160e+202]]

23
[[-1.11505907e+212]
 [-9.54462540e+207]
 [-1.11563255e+208]
 [-6.34902060e+207]
 [-5.88301437e+211]]

24
[[6.83184922e+220]
 [5.84789121e+216]
 [6.83536285e+216]
 [3.88997789e+216]
 [3.60446079e+220]]

25
[[-4.18580189e+229]
 [-3.58294121e+225]
 [-4.18795465e+225]
 [-2.38334838e+225]
 [-2.20841507e+229]]

26
[[2.56459662e+238]
 [2.19523025e+234]
 [2.56591560e+234]
 [1.46025239e+234]
 [1.35307260e+238]]

27
[[-1.57130127e+247]
 [-1.34499440e+243]
 [-1.57210940e+243]
 [-8.94681223e+242]
 [-8.29013296e+246]]

28
[[9.62719701e+255]
 [8.24063867e+251]
 [9.63214829e+251]
 [5.48161740e+251]
 [5.07927694e+255]]

29
[[-5.89848197e+264]
 [-5.04895231e+260]
 [-5.90151557e+260]
 [-3.35852911e+260]
 [-3.11201935e+264]]

30
[[3.61393763e+273]
 [3.09343977e+269]
 [3.61579628e+269]
 [2.05773532e+269]
 [1.90670140e+273]]

31
[[-2.21422143e+282]
 [-1.89531789e+278]
 [-2.21536021e+278]
 [-1.26075271e+278]
 [-1.16821582e+282]]

32
[[1.35663009e+291]
 [1.16124126e+287]
 [1.35732781e+287]
 [7.72449874e+286]
 [7.15753498e+290]]

33
[[-8.31192935e+299]
 [-7.11480260e+295]
 [-8.31620418e+295]
 [-4.73271882e+295]
 [-4.38534612e+299]]

34
[[inf]
 [inf]
 [inf]
 [inf]
 [inf]]

35
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

36
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

37
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

38
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

39
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

40
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

41
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

42
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

43
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

44
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

45
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

46
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

47
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

48
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

49
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

50
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

51
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

52
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

53
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

54
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

55
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

56
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

57
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

58
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

59
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

60
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

61
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

62
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

63
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

64
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

65
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

66
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

67
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

68
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

69
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

70
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

71
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

72
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

73
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

74
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

75
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

76
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

77
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

78
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

79
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

80
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

81
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

82
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

83
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

84
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

85
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

86
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

87
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

88
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

89
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

90
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

91
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

92
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

93
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

94
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

95
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

96
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

97
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

98
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

99
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]

<ipython-input-28-78287e8fc644>:8: RuntimeWarning: invalid value encountered in subtract
  theta=theta-(alpha/m)*l

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan]])